name: CI/CD

on:
  pull_request:
    branches: master

  workflow_dispatch:
jobs:

  build_app:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.17.1

      - name: Install project
        run: npm ci

      - name: Audit npm dependencies
        run: npm audit
        continue-on-error: true

#      - name: Run unit tests
#        shell: bash
#        run: npm test
      - name: build production file
        run: npm run build
      - uses: actions/checkout@v1
      - uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
